---
site_name: Wireless TAC Labs - Deploy 9800-CL in CFME
site_description: Guided lab to go over deploying a WLC 9800-CL in CXLabs CFME
site_author: Tiago Antunes
copyright: Copyright &copy; 2024 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/cisco_logo.png
  favicon: template_assets/cisco_logo.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
#  - with-pdf:
#      cover_title: 9800-CL
#      cover_subtitle: Deploy 9800-CL in CFME
#      cover_logo: template_assets/image.png
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  #- Access: access.md
  - Lab:
      - Overview: overview.md
      - Lab Requirements: lab.md
      - Task 1 - Provision a Virtual Machine (VM) with 9800-CL in CFME: task1.md
      - Task 2 - Configure the basic 9800-CL settings: task2.md
      - Task 3 - Save configuration and upgrade the WLC: task3.md
      - Task 4 - License the WLC: task4.md
      #- Lab Report: Labreport.md
      - Conclusion: conclusion.md
  #- Topologies: topologies.md
dev_addr: 10.88.173.148:8000
